'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */
     await queryInterface.bulkInsert('Users', [{
      //1
        username: 'admin',
        password: '1',
        email: 'admin@gmail.com',
        balance: 0.0,
        imagePath: '/img/logoicon.png',
        isAdmin: true,
        wishlist: [1, 2, 3],
        boughtBooks: [1,5],
        cart: [4,6],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
      {
        username: 'user',
        password: '1',
        email: 'user@gmail.com',
        balance: 0.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [1, 2, 3],
        boughtBooks: [1,5],
        cart: [4,6],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
     }, 
      {
        //3
        username: 'premiumUser',
        password: 'pass123',
        email: 'premium@gmail.com',
        balance: 50.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [1, 2, 3],
        boughtBooks: [1,5],
        cart: [4,6],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
      {
        //4
        username: 'bookLover',
        password: 'readBooks',
        email: 'booklover@gmail.com',
        balance: 0.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [1, 2, 3],
        boughtBooks: [1,5],
        cart: [4,6],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
      {
        //5
        username: 'avidReader',
        password: 'reader123',
        email: 'avidreader@gmail.com',
        balance: 0.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [1, 2, 3],
        boughtBooks: [1, 2, 3],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
      {
        //6
        username: 'fantasyLover',
        password: 'fantasyPass',
        email: 'fantasylover@gmail.com',
        balance: 0.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [1, 2, 3],
        boughtBooks: [1,5],
        cart: [4,6],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
      {
        //7
        username: 'budgetReader',
        password: 'budgetPass',
        email: 'budgetreader@gmail.com',
        balance: 10.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [1, 2, 3],
        boughtBooks: [1,5],
        cart: [4,6],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
      {
        username: 'historyBuff',
        password: 'h1st0ry',
        email: 'historybuff@gmail.com',
        balance: 0.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [1, 2, 3],
        boughtBooks: [1,5],
        cart: [4,6],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
      {
        username: 'platinumUser',
        password: 'plat1num',
        email: 'platinum@gmail.com',
        balance: 100.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [1, 2, 3],
        boughtBooks: [1,5],
        cart: [4,6],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
      {
        username: 'collectorReader',
        password: 'c0ll3ct0r',
        email: 'collectorreader@gmail.com',
        balance: 0.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [1, 2, 3],
        boughtBooks: [4, 5, 6],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
      {
        username: 'sciFiFan',
        password: 's@tUrN',
        email: 'scififan@gmail.com',
        balance: 0.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [1, 2, 3],
        boughtBooks: [1,5],
        cart: [4,6],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
      {
        username: 'user0',
        password: '0',
        email: 'user0@gmail.com',
        balance: 80.0,
        imagePath: '/img/logoicon.png',       
        isAdmin: false,
        wishlist: [0, 1],
        boughtBooks: [5, 9],
        cart: [10, 12],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user1',
        password: '1',
        email: 'user1@gmail.com',
        balance: 35.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [0, 3, 4],
        boughtBooks: [9],
        cart: [13],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user2',
        password: '2',
        email: 'user2@gmail.com',
        balance: 17.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [1],
        boughtBooks: [8, 9, 6],
        cart: [10, 11, 14],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user3',
        password: '3',
        email: 'user3@gmail.com',
        balance: 40.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [1, 4, 0, 3],
        boughtBooks: [9, 7, 6],
        cart: [13, 11],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user4',
        password: '4',
        email: 'user4@gmail.com',
        balance: 58.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [4, 2, 3],
        boughtBooks: [8, 9],
        cart: [11, 14, 10],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user5',
        password: '5',
        email: 'user5@gmail.com',
        balance: 32.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [4, 0, 2, 3, 1],
        boughtBooks: [5, 6],
        cart: [14, 12],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user6',
        password: '6',
        email: 'user6@gmail.com',
        balance: 21.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [2],
        boughtBooks: [8, 6, 9],
        cart: [14],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user7',
        password: '7',
        email: 'user7@gmail.com',
        balance: 90.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [4, 3, 2],
        boughtBooks: [8, 6],
        cart: [12, 10],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user8',
        password: '8',
        email: 'user8@gmail.com',
        balance: 26.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [1],
        boughtBooks: [9, 5, 8],
        cart: [12, 13],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user9',
        password: '9',
        email: 'user9@gmail.com',
        balance: 15.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [0, 4],
        boughtBooks: [7, 6],
        cart: [12, 10],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user10',
        password: '10',
        email: 'user10@gmail.com',
        balance: 72.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [2, 1, 3, 4, 0],
        boughtBooks: [9],
        cart: [11, 13],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user11',
        password: '11',
        email: 'user11@gmail.com',
        balance: 40.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [3, 4, 0],
        boughtBooks: [6],
        cart: [10, 14, 12],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user12',
        password: '12',
        email: 'user12@gmail.com',
        balance: 17.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [1],
        boughtBooks: [8],
        cart: [11, 12],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user13',
        password: '13',
        email: 'user13@gmail.com',
        balance: 59.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [3, 4],
        boughtBooks: [7, 9, 8],
        cart: [12, 13, 14],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user14',
        password: '14',
        email: 'user14@gmail.com',
        balance: 36.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [2],
        boughtBooks: [6],
        cart: [13],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user15',
        password: '15',
        email: 'user15@gmail.com',
        balance: 53.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [1, 2],
        boughtBooks: [5],
        cart: [11],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user16',
        password: '16',
        email: 'user16@gmail.com',
        balance: 12.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [4, 3],
        boughtBooks: [8, 6, 9],
        cart: [11, 13, 10],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user17',
        password: '17',
        email: 'user17@gmail.com',
        balance: 63.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [2, 1, 4, 3, 0],
        boughtBooks: [7, 9, 6],
        cart: [12, 11],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user18',
        password: '18',
        email: 'user18@gmail.com',
        balance: 16.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [3, 2, 4],
        boughtBooks: [9, 6],
        cart: [12, 11],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user19',
        password: '19',
        email: 'user19@gmail.com',
        balance: 19.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [4, 2],
        boughtBooks: [9, 5],
        cart: [13, 10, 11],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user20',
        password: '20',
        email: 'user20@gmail.com',
        balance: 57.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [0, 1, 4, 2, 3],
        boughtBooks: [9],
        cart: [13],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user21',
        password: '21',
        email: 'user21@gmail.com',
        balance: 36.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [1],
        boughtBooks: [5, 9, 7],
        cart: [13],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user22',
        password: '22',
        email: 'user22@gmail.com',
        balance: 35.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [4, 2, 0],
        boughtBooks: [8, 9],
        cart: [12, 13, 14],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user23',
        password: '23',
        email: 'user23@gmail.com',
        balance: 6.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [4, 0, 1],
        boughtBooks: [6, 9],
        cart: [11],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user24',
        password: '24',
        email: 'user24@gmail.com',
        balance: 87.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [0, 1],
        boughtBooks: [9],
        cart: [13, 12, 11],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user25',
        password: '25',
        email: 'user25@gmail.com',
        balance: 34.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [1],
        boughtBooks: [5, 9],
        cart: [10, 11, 13],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user26',
        password: '26',
        email: 'user26@gmail.com',
        balance: 74.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [4, 2, 1, 0, 3],
        boughtBooks: [9],
        cart: [13],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user27',
        password: '27',
        email: 'user27@gmail.com',
        balance: 84.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [4, 3, 1, 2, 0],
        boughtBooks: [9],
        cart: [12, 11],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user28',
        password: '28',
        email: 'user28@gmail.com',
        balance: 39.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [2, 0, 1],
        boughtBooks: [6, 8, 5],
        cart: [14],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      {
        username: 'user29',
        password: '29',
        email: 'user29@gmail.com',
        balance: 97.0,
        imagePath: '/img/logoicon.png',
        isAdmin: false,
        wishlist: [0, 3, 4, 1],
        boughtBooks: [9],
        cart: [12],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    }
      ],
     {});
  },
      async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete('Users', null, {});  

  }
};
