'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */
     await queryInterface.bulkInsert('Users', [{
      //1
        username: 'admin',
        password: '1',
        email: 'admin@gmail.com',
        balance: 0.0,
        imagePath: '/img/logoicon.png',
        isAdmin: true,
        wishlist: [1, 2, 3],
        boughtBooks: [1,5],
        cart: [4,6],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
      {
        username: 'user',
        password: '1',
        email: 'user@gmail.com',
        balance: 75.0,
        imagePath: '/img/clients/c3.png',
        isAdmin: false,
        wishlist: [25, 14],
        boughtBooks: [31, 7, 24, 11, 20],
        cart: [22, 29, 27],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'premiumUser',
        password: 'premiumUser123',
        email: 'premiumUser@gmail.com',
        balance: 72.0,
        imagePath: '/img/clients/c3.png',
        isAdmin: false,
        wishlist: [24, 7, 12],
        boughtBooks: [16, 20, 11, 28],
        cart: [14],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'bookLover',
        password: 'bookLover123',
        email: 'bookLover@gmail.com',
        balance: 11.0,
        imagePath: '/img/clients/c2.png',
        isAdmin: false,
        wishlist: [20],
        boughtBooks: [11, 28],
        cart: [14, 30, 1, 2, 26],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'avidReader',
        password: 'avidReader123',
        email: 'avidReader@gmail.com',
        balance: 43.0,
        imagePath: '/img/clients/c2.png',
        isAdmin: false,
        wishlist: [7],
        boughtBooks: [24],
        cart: [4, 3],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'fantasyLover',
        password: 'fantasyLover123',
        email: 'fantasyLover@gmail.com',
        balance: 76.0,
        imagePath: '/img/clients/person.png',
        isAdmin: false,
        wishlist: [6, 5, 17],
        boughtBooks: [16, 3],
        cart: [11, 10, 18],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'budgetReader',
        password: 'budgetReader123',
        email: 'budgetReader@gmail.com',
        balance: 91.0,
        imagePath: '/img/clients/c1.png',
        isAdmin: false,
        wishlist: [14, 24, 31, 4, 18],
        boughtBooks: [9, 15, 26],
        cart: [17],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'historyBuff',
        password: 'historyBuff123',
        email: 'historyBuff@gmail.com',
        balance: 7.0,
        imagePath: '/img/clients/c3.png',
        isAdmin: false,
        wishlist: [2, 1, 29],
        boughtBooks: [3, 18, 22, 21, 20],
        cart: [14],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'platinumUser',
        password: 'platinumUser123',
        email: 'platinumUser@gmail.com',
        balance: 69.0,
        imagePath: '/img/clients/person.png',
        isAdmin: false,
        wishlist: [9, 8, 28],
        boughtBooks: [20, 4, 6],
        cart: [2, 3],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'collectorReader',
        password: 'collectorReader123',
        email: 'collectorReader@gmail.com',
        balance: 0.0,
        imagePath: '/img/clients/c4.png',
        isAdmin: false,
        wishlist: [13],
        boughtBooks: [29, 8, 17, 24],
        cart: [7, 25],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'sciFiFan',
        password: 'sciFiFan123',
        email: 'sciFiFan@gmail.com',
        balance: 18.0,
        imagePath: '/img/clients/c4.png',
        isAdmin: false,
        wishlist: [13, 25],
        boughtBooks: [31, 26],
        cart: [11, 15, 5, 10],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user0',
        password: 'user0123',
        email: 'user0@gmail.com',
        balance: 82.0,
        imagePath: '/img/clients/c4.png',
        isAdmin: false,
        wishlist: [12, 5],
        boughtBooks: [15, 11],
        cart: [23, 7, 29],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user1',
        password: 'user1123',
        email: 'user1@gmail.com',
        balance: 2.0,
        imagePath: '/img/clients/c4.png',
        isAdmin: false,
        wishlist: [6, 2, 12, 20, 30],
        boughtBooks: [3, 9, 21, 24],
        cart: [19],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user2',
        password: 'user2123',
        email: 'user2@gmail.com',
        balance: 15.0,
        imagePath: '/img/clients/c3.png',
        isAdmin: false,
        wishlist: [25, 27, 21, 17],
        boughtBooks: [31, 28, 3, 14],
        cart: [4, 9, 6, 24],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user3',
        password: 'user3123',
        email: 'user3@gmail.com',
        balance: 43.0,
        imagePath: '/img/clients/c4.png',
        isAdmin: false,
        wishlist: [29, 15, 4],
        boughtBooks: [25, 20, 8, 31, 11],
        cart: [26, 18, 30],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user4',
        password: 'user4123',
        email: 'user4@gmail.com',
        balance: 28.0,
        imagePath: '/img/clients/c4.png',
        isAdmin: false,
        wishlist: [30, 14, 20, 17, 4],
        boughtBooks: [25, 9, 13],
        cart: [3],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user5',
        password: 'user5123',
        email: 'user5@gmail.com',
        balance: 8.0,
        imagePath: '/img/clients/c2.png',
        isAdmin: false,
        wishlist: [21, 9, 30],
        boughtBooks: [3, 17, 8, 12, 24],
        cart: [16, 31, 6],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user6',
        password: 'user6123',
        email: 'user6@gmail.com',
        balance: 53.0,
        imagePath: '/img/clients/c3.png',
        isAdmin: false,
        wishlist: [25, 27, 19],
        boughtBooks: [18],
        cart: [11],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user7',
        password: 'user7123',
        email: 'user7@gmail.com',
        balance: 11.0,
        imagePath: '/img/clients/person.png',
        isAdmin: false,
        wishlist: [6, 2, 12, 21],
        boughtBooks: [28, 19, 7],
        cart: [20, 14, 31],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user8',
        password: 'user8123',
        email: 'user8@gmail.com',
        balance: 14.0,
        imagePath: '/img/clients/c4.png',
        isAdmin: false,
        wishlist: [27, 8, 28],
        boughtBooks: [31, 29, 19, 1, 4],
        cart: [18, 30, 3],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user9',
        password: 'user9123',
        email: 'user9@gmail.com',
        balance: 69.0,
        imagePath: '/img/clients/person.png',
        isAdmin: false,
        wishlist: [31, 18, 10, 12],
        boughtBooks: [5, 27, 3, 19, 2],
        cart: [13, 6, 21, 30],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user10',
        password: 'user10123',
        email: 'user10@gmail.com',
        balance: 84.0,
        imagePath: '/img/clients/c3.png',
        isAdmin: false,
        wishlist: [26, 18, 9, 7],
        boughtBooks: [4, 20, 16],
        cart: [22],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user11',
        password: 'user11123',
        email: 'user11@gmail.com',
        balance: 41.0,
        imagePath: '/img/clients/c2.png',
        isAdmin: false,
        wishlist: [24, 18, 20],
        boughtBooks: [4],
        cart: [15],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user12',
        password: 'user12123',
        email: 'user12@gmail.com',
        balance: 69.0,
        imagePath: '/img/clients/c2.png',
        isAdmin: false,
        wishlist: [12, 15, 19],
        boughtBooks: [23, 13],
        cart: [9, 29, 7],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user13',
        password: 'user13123',
        email: 'user13@gmail.com',
        balance: 70.0,
        imagePath: '/img/clients/c4.png',
        isAdmin: false,
        wishlist: [12, 9, 13],
        boughtBooks: [4, 24, 27, 22],
        cart: [15, 21, 20, 19, 29],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user14',
        password: 'user14123',
        email: 'user14@gmail.com',
        balance: 75.0,
        imagePath: '/img/clients/person.png',
        isAdmin: false,
        wishlist: [31],
        boughtBooks: [19, 1, 7],
        cart: [30],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user15',
        password: 'user15123',
        email: 'user15@gmail.com',
        balance: 94.0,
        imagePath: '/img/clients/person.png',
        isAdmin: false,
        wishlist: [8, 6, 27, 25, 18],
        boughtBooks: [10],
        cart: [21],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user16',
        password: 'user16123',
        email: 'user16@gmail.com',
        balance: 78.0,
        imagePath: '/img/clients/c2.png',
        isAdmin: false,
        wishlist: [24, 27],
        boughtBooks: [23, 28, 20, 13, 31],
        cart: [11, 17, 18, 30],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user17',
        password: 'user17123',
        email: 'user17@gmail.com',
        balance: 63.0,
        imagePath: '/img/clients/person.png',
        isAdmin: false,
        wishlist: [31],
        boughtBooks: [17, 23],
        cart: [21],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user18',
        password: 'user18123',
        email: 'user18@gmail.com',
        balance: 46.0,
        imagePath: '/img/clients/c1.png',
        isAdmin: false,
        wishlist: [8, 25, 23],
        boughtBooks: [9, 31, 29, 13],
        cart: [27],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user19',
        password: 'user19123',
        email: 'user19@gmail.com',
        balance: 96.0,
        imagePath: '/img/clients/c2.png',
        isAdmin: false,
        wishlist: [13, 21],
        boughtBooks: [23, 6, 12, 29, 26],
        cart: [18, 2],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user20',
        password: 'user20123',
        email: 'user20@gmail.com',
        balance: 45.0,
        imagePath: '/img/clients/c1.png',
        isAdmin: false,
        wishlist: [20, 26, 6, 3],
        boughtBooks: [10, 19, 22],
        cart: [27, 30],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user21',
        password: 'user21123',
        email: 'user21@gmail.com',
        balance: 96.0,
        imagePath: '/img/clients/c3.png',
        isAdmin: false,
        wishlist: [27],
        boughtBooks: [5, 9, 1, 31, 20],
        cart: [30, 23, 4, 15, 17],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user22',
        password: 'user22123',
        email: 'user22@gmail.com',
        balance: 24.0,
        imagePath: '/img/clients/c4.png',
        isAdmin: false,
        wishlist: [13, 24, 18, 5],
        boughtBooks: [28],
        cart: [6, 2, 11],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user23',
        password: 'user23123',
        email: 'user23@gmail.com',
        balance: 65.0,
        imagePath: '/img/clients/c4.png',
        isAdmin: false,
        wishlist: [5, 12],
        boughtBooks: [6, 30, 9],
        cart: [1, 24, 10],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user24',
        password: 'user24123',
        email: 'user24@gmail.com',
        balance: 21.0,
        imagePath: '/img/clients/c2.png',
        isAdmin: false,
        wishlist: [6, 16],
        boughtBooks: [9, 19, 21, 25, 4],
        cart: [28, 8, 24, 30],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user25',
        password: 'user25123',
        email: 'user25@gmail.com',
        balance: 51.0,
        imagePath: '/img/clients/person.png',
        isAdmin: false,
        wishlist: [22, 5, 13, 4, 31],
        boughtBooks: [16, 27, 9],
        cart: [11],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user26',
        password: 'user26123',
        email: 'user26@gmail.com',
        balance: 99.0,
        imagePath: '/img/clients/c1.png',
        isAdmin: false,
        wishlist: [25],
        boughtBooks: [7, 16, 6, 14],
        cart: [18, 20, 26],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user27',
        password: 'user27123',
        email: 'user27@gmail.com',
        balance: 12.0,
        imagePath: '/img/clients/c4.png',
        isAdmin: false,
        wishlist: [31, 14, 10],
        boughtBooks: [15, 13],
        cart: [18, 25, 1, 9],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user28',
        password: 'user28123',
        email: 'user28@gmail.com',
        balance: 87.0,
        imagePath: '/img/clients/c4.png',
        isAdmin: false,
        wishlist: [1, 31, 18, 29],
        boughtBooks: [3, 15],
        cart: [19],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
        username: 'user29',
        password: 'user29123',
        email: 'user29@gmail.com',
        balance: 86.0,
        imagePath: '/img/clients/c3.png',
        isAdmin: false,
        wishlist: [23, 8],
        boughtBooks: [2, 9, 28, 27],
        cart: [24, 22, 3, 20, 12],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
      ],
     {});
  },
      async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete('Users', null, {});  

  }
};
