'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */
    await queryInterface.bulkInsert('Books', [

      {
        title: 'One Piece',
        owner: 'historyBuff',
        ownerId: 8,
        author: 'Oda',
        imagePath: '/img/explore/e2.jpg',
        filePath: '',
        price: 33.0,
        tags: ['Science Fiction', 'Historical Fiction'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [20, 26, 33],
        reviews: [1, 32],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'Two Pieces',
        owner: 'user5',
        ownerId: 17,
        author: 'Oda',
        imagePath: '/img/explore/b1.jpg',
        filePath: '',
        price: 46.0,
        tags: ['Adventure', 'Drama', 'Fantasy', 'Mystery', 'Science Fiction'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [1, 21, 41],
        reviews: [2, 33],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'Naruto',
        owner: 'user29',
        ownerId: 41,
        author: 'Masashi Kishimoto',
        imagePath: '/img/explore/b1.jpg',
        filePath: '',
        price: 95.0,
        tags: ['Fantasy', 'Mystery', 'Historical Fiction'],
        isVerified: false,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [6, 8, 13, 14, 17, 21, 40],
        reviews: [3, 34],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'Harry Potter',
        owner: 'user1',
        ownerId: 13,
        author: 'J.K. Rowling',
        imagePath: '/img/explore/b1.jpg',
        filePath: '',
        price: 98.0,
        tags: ['Fantasy', 'Contemporary', 'Mystery', 'Adventure'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [9, 20, 22, 23, 25, 36],
        reviews: [4, 35],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'The Hunger Games',
        owner: 'fantasyLover',
        ownerId: 6,
        author: 'Suzanne Collins',
        imagePath: '/img/explore/b1.jpg',
        filePath: '',
        price: 63.0,
        tags: ['Historical Fiction', 'Magical Realism'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [21, 33],
        reviews: [5, 36],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'Lord of the Rings',
        owner: 'user15',
        ownerId: 27,
        author: 'J.R.R. Tolkien',
        imagePath: '/img/explore/e1.jpg',
        filePath: '',
        price: 1.0,
        tags: ['Contemporary', 'Horror', 'Romance', 'Magical Realism'],
        isVerified: false,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [9, 31, 35, 38],
        reviews: [6, 37],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'Game of Thrones',
        owner: 'user13',
        ownerId: 25,
        author: 'George R.R. Martin',
        imagePath: '/img/explore/b4.jpg',
        filePath: '',
        price: 72.0,
        tags: ['Horror', 'Mystery', 'Historical Fiction', 'Satire'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [2, 19, 26, 38],
        reviews: [7, 38],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'Dune',
        owner: 'user14',
        ownerId: 26,
        author: 'Frank Herbert',
        imagePath: '/img/explore/e6.jpg',
        filePath: '',
        price: 97.0,
        tags: ['Fantasy', 'Mystery', 'Romance'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [10, 15, 17],
        reviews: [8, 39],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'The Great Gatsby',
        owner: 'user',
        ownerId: 2,
        author: 'F. Scott Fitzgerald',
        imagePath: '/img/explore/e5.jpg',
        filePath: '',
        price: 87.0,
        tags: ['Classic', 'Thriller', 'Romance'],
        isVerified: false,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [1, 7, 13, 16, 30, 33, 35, 36, 37, 41],
        reviews: [9, 40],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'To Kill a Mockingbird',
        owner: 'user16',
        ownerId: 28,
        author: 'Harper Lee',
        imagePath: '/img/explore/e4.jpg',
        filePath: '',
        price: 46.0,
        tags: ['Historical Fiction', 'Mystery', 'Dystopian'],
        isVerified: false,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [27, 32],
        reviews: [10, 41],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'The Catcher in the Rye',
        owner: 'user27',
        ownerId: 39,
        author: 'J.D. Salinger',
        imagePath: '/img/explore/e3.jpg',
        filePath: '',
        price: 95.0,
        tags: ['Historical Fiction', 'Dystopian', 'Historical Fiction', 'Fantasy'],
        isVerified: false,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [1, 2, 3, 4, 12, 15],
        reviews: [11, 42],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'The Catcher in the Rye',
        owner: 'user18',
        ownerId: 30,
        author: 'J.D. Salinger',
        imagePath: '/img/explore/b1.jpg',
        filePath: '',
        price: 43.0,
        tags: ['Historical Fiction', 'Horror', 'Mystery', 'Science Fiction', 'Historical Fiction'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [17, 31],
        reviews: [12, 43],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'To Kill a Mockingbird',
        owner: 'avidReader',
        ownerId: 5,
        author: 'Harper Lee',
        imagePath: '/img/explore/b4.jpg',
        filePath: '',
        price: 1.0,
        tags: ['Fantasy', 'Satire', 'Philosophical', 'Drama', 'Historical Fiction'],
        isVerified: false,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [16, 24, 28, 30, 39],
        reviews: [13, 44],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: '1984',
        owner: 'user0',
        ownerId: 12,
        author: 'George Orwell',
        imagePath: '/img/explore/b4.jpg',
        filePath: '',
        price: 9.0,
        tags: ['Drama', 'Philosophical', 'Satire', 'Science Fiction', 'Magical Realism'],
        isVerified: false,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [14, 38],
        reviews: [14, 45],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'The Great Gatsby',
        owner: 'user14',
        ownerId: 26,
        author: 'F. Scott Fitzgerald',
        imagePath: '/img/explore/e2.jpg',
        filePath: '',
        price: 78.0,
        tags: ['Historical Fiction', 'Mystery', 'Dystopian', 'Magical Realism'],
        isVerified: false,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [7, 12, 39, 40],
        reviews: [15, 46],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'Pride and Prejudice',
        owner: 'user28',
        ownerId: 40,
        author: 'Jane Austen',
        imagePath: '/img/explore/e1.jpg',
        filePath: '',
        price: 92.0,
        tags: ['Philosophical', 'Fantasy', 'Historical Fiction'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [3, 6, 22, 37, 38],
        reviews: [16, 47],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'The Hobbit',
        owner: 'user26',
        ownerId: 38,
        author: 'J.R.R. Tolkien',
        imagePath: '/img/explore/b3.jpg',
        filePath: '',
        price: 96.0,
        tags: ['Adventure', 'Drama', 'Science Fiction'],
        isVerified: false,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [10, 17, 29],
        reviews: [17, 48],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'Harry Potter and the Sorcerer\'s Stone',
        owner: 'user23',
        ownerId: 35,
        author: 'J.K. Rowling',
        imagePath: '/img/explore/e3.jpg',
        filePath: '',
        price: 58.0,
        tags: ['Dystopian', 'Contemporary', 'Fantasy', 'Historical Fiction', 'Classic'],
        isVerified: false,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [1, 8, 18],
        reviews: [18, 49],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'The Lord of the Rings',
        owner: 'user29',
        ownerId: 41,
        author: 'J.R.R. Tolkien',
        imagePath: '/img/explore/e4.jpg',
        filePath: '',
        price: 44.0,
        tags: ['Science Fiction', 'Adventure', 'Science Fiction', 'Mystery', 'Young Adult'],
        isVerified: false,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [19, 20, 21, 26, 32, 36],
        reviews: [19, 50],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'Fahrenheit 451',
        owner: 'user15',
        ownerId: 27,
        author: 'Ray Bradbury',
        imagePath: '/img/explore/e5.jpg',
        filePath: '',
        price: 63.0,
        tags: ['Science Fiction', 'Satire'],
        isVerified: false,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [2, 3, 8, 9, 15, 22, 28, 33],
        reviews: [20],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'Brave New World',
        owner: 'user17',
        ownerId: 29,
        author: 'Aldous Huxley',
        imagePath: '/img/explore/e3.jpg',
        filePath: '',
        price: 46.0,
        tags: ['Classic', 'Drama', 'Thriller', 'Dystopian'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [8, 13, 36],
        reviews: [21],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'The Chronicles of Narnia',
        owner: 'user',
        ownerId: 2,
        author: 'C.S. Lewis',
        imagePath: '/img/explore/e6.jpg',
        filePath: '',
        price: 49.0,
        tags: ['Contemporary', 'Science Fiction', 'Drama', 'Magical Realism'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [8, 25, 32],
        reviews: [22],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'The Hunger Games',
        owner: 'user18',
        ownerId: 30,
        author: 'Suzanne Collins',
        imagePath: '/img/explore/b1.jpg',
        filePath: '',
        price: 83.0,
        tags: ['Fantasy', 'Satire', 'Thriller'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [24, 28, 29, 31],
        reviews: [23],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'The Da Vinci Code',
        owner: 'premiumUser',
        ownerId: 3,
        author: 'Dan Brown',
        imagePath: '/img/explore/e4.jpg',
        filePath: '',
        price: 65.0,
        tags: ['Drama', 'Thriller', 'Young Adult', 'Mystery'],
        isVerified: false,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [2, 5, 10, 13, 17, 25],
        reviews: [24],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'The Alchemist',
        owner: 'budgetReader',
        ownerId: 7,
        author: 'Paulo Coelho',
        imagePath: '/img/explore/e1.jpg',
        filePath: '',
        price: 57.0,
        tags: ['Drama', 'Mystery', 'Classic', 'Historical Fiction', 'Romance'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [15, 16, 36],
        reviews: [25],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'The Shining',
        owner: 'user24',
        ownerId: 36,
        author: 'Stephen King',
        imagePath: '/img/explore/b4.jpg',
        filePath: '',
        price: 65.0,
        tags: ['Philosophical', 'Classic', 'Magical Realism', 'Dystopian', 'Romance'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [7, 11, 31],
        reviews: [26],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'One Hundred Years of Solitude',
        owner: 'admin',
        ownerId: 1,
        author: 'Gabriel Garcia Marquez',
        imagePath: '/img/explore/e2.jpg',
        filePath: '',
        price: 94.0,
        tags: ['Historical Fiction', 'Satire', 'Horror', 'Adventure'],
        isVerified: false,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [21, 25, 37, 41],
        reviews: [27],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'The Kite Runner',
        owner: 'avidReader',
        ownerId: 5,
        author: 'Khaled Hosseini',
        imagePath: '/img/explore/e5.jpg',
        filePath: '',
        price: 67.0,
        tags: ['Philosophical', 'Contemporary'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [1, 3, 4, 14, 19, 28, 34, 41],
        reviews: [28],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'The Hitchhiker\'s Guide to the Galaxy',
        owner: 'user28',
        ownerId: 40,
        author: 'Douglas Adams',
        imagePath: '/img/explore/e3.jpg',
        filePath: '',
        price: 14.0,
        tags: ['Fantasy', 'Mystery', 'Adventure', 'Young Adult', 'Drama'],
        isVerified: false,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [10, 20, 30, 31],
        reviews: [29],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'The Grapes of Wrath',
        owner: 'user0',
        ownerId: 12,
        author: 'John Steinbeck',
        imagePath: '/img/explore/e5.jpg',
        filePath: '',
        price: 77.0,
        tags: ['Mystery', 'Young Adult', 'Science Fiction'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [35],
        reviews: [30],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
    {
        title: 'The Color Purple',
        owner: 'platinumUser',
        ownerId: 9,
        author: 'Alice Walker',
        imagePath: '/img/explore/b4.jpg',
        filePath: '',
        price: 38.0,
        tags: ['Satire', 'Contemporary', 'Fantasy', 'Thriller'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [2, 11, 14, 15, 20, 28, 30, 33],
        reviews: [31],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },  
  ],
     {});
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete('Books', null, {});  

  }
};
