'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */
    await queryInterface.bulkInsert('Books', [{
      title:'One Piece',
      owner:'KimDong',
      ownerId:1,
      author:'Oda',
      imagePath:'/img/explore/e1.jpg',
      price:16,
      tags: ['Comedy', 'Action', 'Fantasy'],
      isVerified: true,
      description:'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [2,5,6],
      reviews: [1,3],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
     }, 
     {
      title:'Two Pieces',
      owner:'KimDong',
      ownerId:1,
      author:'Oda',
      imagePath:'/img/explore/e1.jpg',
      price:16,
      tags: ['Comedy', 'Action', 'Fantasy'],
      isVerified: true,
      description:'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer:[2,5,6],
      reviews: [1,3],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
     },
     {
      title: 'Naruto',
      owner: 'VizMedia',
      ownerId: 2,
      author: 'Masashi Kishimoto',
      imagePath: '/img/explore/e1.jpg',
      price: 20,
      tags: ['Action', 'Adventure'],
      isVerified: true,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [2,5,6],
      reviews: [1,3],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
      },
      {
        title: 'Harry Potter',
        owner: 'Scholastic',
        ownerId: 3,
        author: 'J.K. Rowling',
        imagePath: '/img/explore/e1.jpg',
        price: 25,
        tags: ['Fantasy', 'Magic'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [2,5,6],
        reviews: [1,3],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
      {
        title: 'The Hunger Games',
        owner: 'Suzanne Collins',
        ownerId: 2,
        author: 'Suzanne Collins',
        imagePath: '/img/explore/e1.jpg',
        price: 18,
        tags: ['Dystopian', 'Adventure'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [2,5,6],
        reviews: [1,3],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
      {
        title: 'Lord of the Rings',
        owner: 'HarperCollins',
        ownerId: 1,
        author: 'J.R.R. Tolkien',
        imagePath: '/img/explore/e1.jpg',
        price: 30,
        tags: ['Fantasy', 'Adventure'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [2,5,6],
        reviews: [1,3],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
      {
        title: 'Game of Thrones',
        owner: 'Bantam Books',
        ownerId: 3,
        author: 'George R.R. Martin',
        imagePath: '/img/explore/e1.jpg',
        price: 28,
        tags: ['Fantasy', 'Drama'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [2,5,6],
        reviews: [1,3],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
      {
        title: 'Dune',
        owner: 'Ace Books',
        ownerId: 3,
        author: 'Frank Herbert',
        imagePath: '/img/explore/e1.jpg',
        price: 22,
        tags: ['Science Fiction', 'Adventure'],
        isVerified: true,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [2,5,6],
        reviews: [1,3],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
      {
        title: 'The Great Gatsby',
        owner: 'Scribner',
        ownerId: 8,
        author: 'F. Scott Fitzgerald',
        imagePath: '/img/explore/e1.jpg',
        price: 15,
        tags: ['Classic', 'Romance'],
        isVerified: false,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [2,5,6],
        reviews: [1,3],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },    
      {
        title: 'To Kill a Mockingbird',
        owner: 'Harper Lee',
        ownerId: 7,
        author: 'Harper Lee',
        imagePath: '/img/explore/e1.jpg',
        price: 17,
        tags: ['Classic', 'Drama'],
        isVerified: false,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [2,5,6],
        reviews: [1,3],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
      },
      {
        title: 'The Catcher in the Rye',
        owner: 'J.D. Salinger',
        ownerId: 5,
        author: 'J.D. Salinger',
        imagePath: '/img/explore/e1.jpg',
        price: 19,
        tags: ['Classic', 'Coming of Age'],
        isVerified: false,
        description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
        buyer: [2,5,6],
        reviews: [1,3],
        createdAt: Sequelize.literal('NOW()'),
        updatedAt: Sequelize.literal('NOW()'),
    },
    {
      title: 'The Catcher in the Rye',
      owner: 'platinumUser',
      ownerId: 9,
      author: 'J.D. Salinger',
      imagePath: '/img/explore/e1.jpg',
      price: 86.0,
      tags: ['Science Fiction', 'Mystery', 'Classic'],
      isVerified: false,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [19, 7, 27, 6],
      reviews: [13, 28],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      title: 'To Kill a Mockingbird',
      owner: 'user19',
      ownerId: 31,
      author: 'Harper Lee',
      imagePath: '/img/explore/e5.jpg',
      price: 36.0,
      tags: ['Classic', 'Fantasy'],
      isVerified: false,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [22, 1, 29],
      reviews: [10, 4, 1, 11],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      title: '1984',
      owner: 'user15',
      ownerId: 27,
      author: 'George Orwell',
      imagePath: '/img/explore/e3.jpg',
      price: 51.0,
      tags: ['Historical Fiction', 'Fantasy', 'Satire', 'Horror', 'Science Fiction'],
      isVerified: true,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [12, 34],
      reviews: [16, 37, 4, 7],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      title: 'The Great Gatsby',
      owner: 'user11',
      ownerId: 23,
      author: 'F. Scott Fitzgerald',
      imagePath: '/img/explore/e3.jpg',
      price: 11.0,
      tags: ['Classic', 'Young Adult'],
      isVerified: false,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [39, 11],
      reviews: [2],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      title: 'Pride and Prejudice',
      owner: 'user19',
      ownerId: 31,
      author: 'Jane Austen',
      imagePath: '/img/explore/e1.jpg',
      price: 89.0,
      tags: ['Science Fiction', 'Classic', 'Thriller', 'Fantasy'],
      isVerified: false,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [22, 16, 10],
      reviews: [15, 25, 34],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      title: 'The Hobbit',
      owner: 'user3',
      ownerId: 15,
      author: 'J.R.R. Tolkien',
      imagePath: '/img/explore/e2.jpg',
      price: 18.0,
      tags: ['Mystery', 'Satire', 'Magical Realism'],
      isVerified: true,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [30, 31],
      reviews: [3, 26, 31],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      title: 'Harry Potter and the Sorcerer\'s Stone',
      owner: 'user20',
      ownerId: 32,
      author: 'J.K. Rowling',
      imagePath: '/img/explore/e4.jpg',
      price: 79.0,
      tags: ['Philosophical', 'Magical Realism'],
      isVerified: true,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [38, 2],
      reviews: [29, 33, 14, 9],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      title: 'The Lord of the Rings',
      owner: 'user22',
      ownerId: 34,
      author: 'J.R.R. Tolkien',
      imagePath: '/img/explore/person.png',
      price: 76.0,
      tags: ['Satire', 'Romance', 'Horror'],
      isVerified: true,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [29, 34, 35, 8, 9],
      reviews: [10, 20, 13],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      title: 'Fahrenheit 451',
      owner: 'user16',
      ownerId: 28,
      author: 'Ray Bradbury',
      imagePath: '/img/explore/e6.jpg',
      price: 63.0,
      tags: ['Thriller', 'Satire', 'Fantasy'],
      isVerified: true,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [22, 15, 36, 13],
      reviews: [5],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      title: 'Brave New World',
      owner: 'user1',
      ownerId: 13,
      author: 'Aldous Huxley',
      imagePath: '/img/explore/e2.jpg',
      price: 32.0,
      tags: ['Dystopian', 'Magical Realism', 'Fantasy', 'Horror'],
      isVerified: false,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [36, 22, 25],
      reviews: [11],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      title: 'The Chronicles of Narnia',
      owner: 'historyBuff',
      ownerId: 8,
      author: 'C.S. Lewis',
      imagePath: '/img/explore/e5.jpg',
      price: 48.0,
      tags: ['Mystery', 'Adventure', 'Satire', 'Classic', 'Historical Fiction'],
      isVerified: false,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [8, 19],
      reviews: [27, 18, 40],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      title: 'The Hunger Games',
      owner: 'user29',
      ownerId: 41,
      author: 'Suzanne Collins',
      imagePath: '/img/explore/e3.jpg',
      price: 88.0,
      tags: ['Magical Realism', 'Fantasy', 'Horror', 'Mystery'],
      isVerified: true,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [6],
      reviews: [11, 8],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      title: 'The Da Vinci Code',
      owner: 'user0',
      ownerId: 12,
      author: 'Dan Brown',
      imagePath: '/img/explore/e5.jpg',
      price: 80.0,
      tags: ['Science Fiction', 'Magical Realism', 'Historical Fiction'],
      isVerified: true,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [2],
      reviews: [28, 29, 31, 19, 32],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      title: 'The Alchemist',
      owner: 'user15',
      ownerId: 27,
      author: 'Paulo Coelho',
      imagePath: '/img/explore/e2.jpg',
      price: 96.0,
      tags: ['Science Fiction', 'Romance', 'Philosophical', 'Young Adult'],
      isVerified: false,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [35],
      reviews: [1, 19, 18],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      title: 'The Shining',
      owner: 'admin',
      ownerId: 1,
      author: 'Stephen King',
      imagePath: '/img/explore/person.png',
      price: 39.0,
      tags: ['Fantasy', 'Magical Realism', 'Adventure'],
      isVerified: false,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [2],
      reviews: [12],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      title: 'One Hundred Years of Solitude',
      owner: 'user17',
      ownerId: 29,
      author: 'Gabriel Garcia Marquez',
      imagePath: '/img/explore/e5.jpg',
      price: 59.0,
      tags: ['Mystery', 'Young Adult', 'Dystopian'],
      isVerified: false,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [2, 11, 6, 9, 15],
      reviews: [1, 2, 16, 18],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      title: 'The Kite Runner',
      owner: 'user26',
      ownerId: 38,
      author: 'Khaled Hosseini',
      imagePath: '/img/explore/e6.jpg',
      price: 2.0,
      tags: ['Young Adult', 'Science Fiction', 'Contemporary'],
      isVerified: false,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [25, 18, 7, 15],
      reviews: [29, 6],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      title: 'The Hitchhiker\'s Guide to the Galaxy',
      owner: 'user27',
      ownerId: 39,
      author: 'Douglas Adams',
      imagePath: '/img/explore/e3.jpg',
      price: 11.0,
      tags: ['Historical Fiction', 'Young Adult'],
      isVerified: false,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [25, 39, 10, 31, 29],
      reviews: [9, 31, 17, 14, 3],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      title: 'The Grapes of Wrath',
      owner: 'user28',
      ownerId: 40,
      author: 'John Steinbeck',
      imagePath: '/img/explore/e2.jpg',
      price: 12.0,
      tags: ['Romance', 'Magical Realism', 'Fantasy', 'Mystery', 'Classic'],
      isVerified: false,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [19, 40, 29, 27],
      reviews: [4, 12],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      title: 'The Color Purple',
      owner: 'user9',
      ownerId: 21,
      author: 'Alice Walker',
      imagePath: '/img/explore/e2.jpg',
      price: 19.0,
      tags: ['Science Fiction', 'Science Fiction'],
      isVerified: false,
      description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      buyer: [34, 31, 1],
      reviews: [18, 14, 9],
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
  ],
     {});
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete('Books', null, {});  

  }
};
