'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */
    await queryInterface.bulkInsert('Reports', [{
      userId: 2,
      reportedBookId: null,
      reportedUserId: 1,
      isBook:false,
      content:'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 2,
      reportedBookId: null,
      reportedUserId: 7,
      isBook:false,
      content:'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 3,
      reportedBookId: 2,
      reportedUserId: null,
      isBook: true,
      content: 'I found some inappropriate content in this book. Please review.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 4,
      reportedBookId: null,
      reportedUserId: 3,
      isBook: false,
      content: 'I encountered a user with inappropriate behavior. Please take action.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 5,
      reportedBookId: 4,
      reportedUserId: null,
      isBook: true,
      content: 'This book seems to have a spoiler in the reviews. Please address.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {

      userId: 6,
      reportedBookId: null,
      reportedUserId: 5,
      isBook: false,
      content: 'The reported user is spamming unrelated content. Please investigate.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 7,
      reportedBookId: 6,
      reportedUserId: null,
      isBook: true,
      content: 'This book review seems to contain offensive language. Please take a look.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 12,
      reportedBookId: 12,
      reportedUserId: null,
      isBook: true,
      content: 'This book contains inappropriate content.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 29,
      reportedBookId: null,
      reportedUserId: 12,
      isBook: false,
      content: 'This user engages in offensive language and behavior.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 6,
      reportedBookId: 19,
      reportedUserId: null,
      isBook: true,
      content: 'The information in this book is misleading.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 35,
      reportedBookId: null,
      reportedUserId: 6,
      isBook: false,
      content: 'User consistently violates community guidelines.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 18,
      reportedBookId: 9,
      reportedUserId: null,
      isBook: true,
      content: 'Reported for spamming and irrelevant content.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 23,
      reportedBookId: null,
      reportedUserId: 18,
      isBook: false,
      content: 'Reported for harassment or bullying of other users.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 33,
      reportedBookId: 10,
      reportedUserId: null,
      isBook: true,
      content: 'Possible violation of intellectual property rights.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 8,
      reportedBookId: null,
      reportedUserId: 33,
      isBook: false,
      content: 'Inappropriate comments and interactions with others.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 14,
      reportedBookId: 11,
      reportedUserId: null,
      isBook: true,
      content: 'Book appears to be a duplicate or plagiarized.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 27,
      reportedBookId: null,
      reportedUserId: 14,
      isBook: false,
      content: 'Spamming and excessive self-promotion by this user.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 26,
      reportedBookId: 11,
      reportedUserId: null,
      isBook: true,
      content: 'Inaccurate categorization of the book genre.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 15,
      reportedBookId: null,
      reportedUserId: 26,
      isBook: false,
      content: 'User is involved in fake accounts or review manipulation.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 13,
      reportedBookId: 3,
      reportedUserId: null,
      isBook: true,
      content: 'Contains offensive language or hate speech.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 28,
      reportedBookId: null,
      reportedUserId: 13,
      isBook: false,
      content: 'Persistent trolling and disruption of community discussions.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 7,
      reportedBookId: 17,
      reportedUserId: null,
      isBook: true,
      content: 'Book seems to encourage harmful behavior.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 34,
      reportedBookId: null,
      reportedUserId: 7,
      isBook: false,
      content: 'Engaging in hate speech or discriminatory behavior.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 27,
      reportedBookId: 1,
      reportedUserId: null,
      isBook: true,
      content: 'Suspicion of fake reviews or ratings manipulation.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 14,
      reportedBookId: null,
      reportedUserId: 27,
      isBook: false,
      content: 'Suspected use of multiple accounts to manipulate ratings.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 38,
      reportedBookId: 14,
      reportedUserId: null,
      isBook: true,
      content: 'Issues with the book formatting or readability.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 3,
      reportedBookId: null,
      reportedUserId: 38,
      isBook: false,
      content: 'Repeatedly ignores warnings and guidance.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 9,
      reportedBookId: 4,
      reportedUserId: null,
      isBook: true,
      content: 'Book violates community guidelines.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 32,
      reportedBookId: null,
      reportedUserId: 9,
      isBook: false,
      content: 'User spreading false information and causing confusion.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 17,
      reportedBookId: 9,
      reportedUserId: null,
      isBook: true,
      content: 'Concerns about the accuracy of the book\'s information.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 24,
      reportedBookId: null,
      reportedUserId: 17,
      isBook: false,
      content: 'This user appears to be engaging in fraudulent activities.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 3,
      reportedBookId: 14,
      reportedUserId: null,
      isBook: true,
      content: 'Reported for inappropriate cover image.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 38,
      reportedBookId: null,
      reportedUserId: 3,
      isBook: false,
      content: 'Inappropriate profile image or username.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 25,
      reportedBookId: 4,
      reportedUserId: null,
      isBook: true,
      content: 'Excessive use of explicit or mature content.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 16,
      reportedBookId: null,
      reportedUserId: 25,
      isBook: false,
      content: 'Persistent issues with soliciting or sharing personal information.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 26,
      reportedBookId: 16,
      reportedUserId: null,
      isBook: true,
      content: 'Possible violation of copyright laws.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 15,
      reportedBookId: null,
      reportedUserId: 26,
      isBook: false,
      content: 'Concerns about the user\'s reliability or trustworthiness.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 29,
      reportedBookId: 17,
      reportedUserId: null,
      isBook: true,
      content: 'Misleading title or false advertising.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 12,
      reportedBookId: null,
      reportedUserId: 29,
      isBook: false,
      content: 'User consistently ignores or dismisses constructive feedback.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 38,
      reportedBookId: 18,
      reportedUserId: null,
      isBook: true,
      content: 'Inappropriate or explicit scenes in the book.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 3,
      reportedBookId: null,
      reportedUserId: 38,
      isBook: false,
      content: 'Engaging in aggressive or threatening behavior.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 20,
      reportedBookId: 11,
      reportedUserId: null,
      isBook: true,
      content: 'The book may be a scam or fraudulent.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 21,
      reportedBookId: null,
      reportedUserId: 20,
      isBook: false,
      content: 'Violation of privacy or inappropriate stalking behavior.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 32,
      reportedBookId: 10,
      reportedUserId: null,
      isBook: true,
      content: 'Reported for being a pirated or illegal copy.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 9,
      reportedBookId: null,
      reportedUserId: 32,
      isBook: false,
      content: 'Reported for attempting to manipulate user reviews.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 33,
      reportedBookId: 12,
      reportedUserId: null,
      isBook: true,
      content: 'Other concerns not covered by existing categories.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
    {
      userId: 8,
      reportedBookId: null,
      reportedUserId: 33,
      isBook: false,
      content: 'Other concerns not covered by existing categories.',
      createdAt: Sequelize.literal('NOW()'),
      updatedAt: Sequelize.literal('NOW()'),
    },
  ], {});
 
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * 
     */
    await queryInterface.bulkDelete('Reports', null, {});  
  }
};
